// cmd-k-engine/src/components/react/CommandItem.tsx
import type { Command } from '../../types/command'

interface Props {
  command: Command
  active: boolean
  onSelect: () => void
  onHover: () => void
}

export function CommandItem({ command, active, onSelect, onHover }: Props) {
  return (
    <button
      type="button"
      className={`command${active ? ' active' : ''}`}
      role="option"
      aria-selected={active}
      onMouseEnter={onHover}
      onClick={onSelect}
    >
      <span className="command-content">
        <strong>{command.label}</strong>
        {command.description && <small>{command.description}</small>}
      </span>
      {command.children?.length ? <span className="arrow" aria-hidden="true">→</span> : null}
    </button>
  )
}

// cmd-k-engine/src/components/CommandItem.vue
<script setup lang="ts">
import type { Command } from '@/types/command'

defineProps<{
  command: Command
  active: boolean
}>()

const emit = defineEmits<{
  select: []
  hover: []
}>()
</script>

<template>
  <button
    type="button"
    class="command"
    :class="{ active }"
    role="option"
    :aria-selected="active"
    @mouseenter="emit('hover')"
    @click="emit('select')"
  >
    <span class="command-content">
      <strong>
        {{ command.label }}
      </strong>

      <small
        v-if="command.description"
      >
        {{ command.description }}
      </small>
    </span>

    <!-- Indicates that this command
         opens a submenu. -->
    <span
      v-if="command.children?.length"
      class="arrow"
      aria-hidden="true"
    >
      →
    </span>
  </button>
</template>
