// cmd-k-engine/src/components/react/CommandBreadcrumbs.tsx
export function CommandBreadcrumbs({ breadcrumbs }: { breadcrumbs: string[] }) {
  return (
    <div className="breadcrumbs">
      <span>Commands</span>
      {breadcrumbs.map((breadcrumb) => (
        <span key={breadcrumb}>
          <span aria-hidden="true"> / </span>
          {breadcrumb}
        </span>
      ))}
    </div>
  )
}

// cmd-k-engine/src/components/CommandBreadcrumbs.vue
<script setup lang="ts">
defineProps<{
  breadcrumbs: string[]
}>()
</script>

<template>
  <div class="breadcrumbs">
    <span>Commands</span>

    <template
      v-for="breadcrumb in breadcrumbs"
      :key="breadcrumb"
    >
      <span aria-hidden="true">
        /
      </span>

      <span>
        {{ breadcrumb }}
      </span>
    </template>
  </div>
</template>
